### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by EsioFreitas** [UnBArqDsw/2020.1_G5_Diario_da_Saude#1]
**Visão geral**
Não tem nada no repositório. A matéria é puxada e parece que estão atrasados.

**Comment by gustavocarvalho1002** [comment]
Prezado, verifique na branch **docs**, pois desde de sexta já tinha documentos lá.

**Comment by EsioFreitas** [comment]
Prezado, os feedbacks serão dados para o que esta na master

**Comment by EsioFreitas** [comment]
**Visão Geral** 
Sei que ainda está em desenvolvimento, mas seria legal ja ter um resumo do projeto de vcs. Parabéns pelo o histórico de edição, isso é muito bom, porém as referencias dos documentos também são importantes. A wiki eh muito bonita haha e as cores tbm. Muito bom que vcs estão mostrando o porquê das técnicas em casa começo de documentos. Por fim, falta versionamento! Cade as versões de cada artefato? como eles evoluiram? Eles evoluiram? 

**Brainstorm** 
Muito bom!

**5W2H** 
Não há nada

**Rich Picture** 
Estão bonitos, mas podem ser melhorados. Falta os fluxos de volta das ações e as troca entre eles.

"Plano de Análise Esforço e Tempo"
Muito bom! Parabens.

"Controle de Risco"
O artefato esta incompleto ainda. Mas ta indo por um bom caminho. Deixe claro nele quais são os riscos que vcs vão mitigar e como.

"Mapa Mental"
Muito bom"
