### ISSUE TITLE
T03 - CRIAR ENDPOINT DE LISTAR TODAS UBS

### ISSUE THREAD

**Issue by GabrielTiveron** [UnBArqDsw/2020.1_G5_Diario_da_Saude#14]
## Tarefa/Atividade
Criação de endpoint para obtenção de todas as UBS's

## Critérios 
- [x] Criar endpoint
- [x] Tratar possíveis erros
- [x] Retornar uma listagem de UBS's

**Comment by gustavocarvalho1002** [comment]
Endpoint criado com sucesso. Segue abaixo a lista das rotas:


Listar todas as ubs:        http://localhost:8080/ubs
Listar ubs por id:            http://localhost:8080/ubs/:id

**Comment by gustavocarvalho1002** [comment]
![image](https://user-images.githubusercontent.com/23438547/96655563-34244d00-1314-11eb-8b3f-66252b8aed03.png)
