### ISSUE TITLE
T09 - CRIAR AMBIENTE DE DESENVOLVIMENTO DO BANCO DE DADOS

### ISSUE THREAD

**Issue by gustavocarvalho1002** [UnBArqDsw/2020.1_G5_Diario_da_Saude#15]
## Tarefa/Atividade
Criar ambiente de desenvolvimento do banco com docker-compose.

## Critérios 
- [x] MongoDB
- [x] Mongo Express
- [x] Docker Compose

**Comment by Rdadamos** [comment]
Acessar Mongo Express em 0.0.0.0:8081
