### ISSUE TITLE
T10 - CRIAR AMBIENTE DE DESENVOLVIMENTO DO BACKEND

### ISSUE THREAD

**Issue by gustavocarvalho1002** [UnBArqDsw/2020.1_G5_Diario_da_Saude#16]
## Tarefa/Atividade
Criar ambiente de desenvolvimento do backend com docker-compose.

## Critérios 
- [x] Node
- [x] Express
- [x] Docker Compose

**Comment by Rdadamos** [comment]
Backend em 0.0.0.0:8080
