### ISSUE TITLE
T11 - CRIAR AMBIENTE DE DESENVOLVIMENTO DA APLICAÇÃO FRONTEND

### ISSUE THREAD

**Issue by gustavocarvalho1002** [UnBArqDsw/2020.1_G5_Diario_da_Saude#17]
## Tarefa/Atividade
Dockerizar a aplicação de front-end

## Critérios 
- [x] Build com Expo
- [x] Docker Compose

**Comment by Rdadamos** [comment]
O endereço estará no QR Code no terminal para ser acessado pelo Expo.
