### ISSUE TITLE
T07 - CRIAR ENDPOINT DE CADASTRO DE GRUPO

### ISSUE THREAD

**Issue by GabrielTiveron** [UnBArqDsw/2020.1_G5_Diario_da_Saude#8]
## Tarefa/Atividade
Criar um ponto na API para possibilitar o cadastro dos grupos.

## Critérios 
- [x] Receber informações
- [x] Validar informações
- [x] Cadastrar informações no banco
- [x] Retornar status de erro, caso houver

**Comment by gustavocarvalho1002** [comment]
Endpoint de cadastro de grupo foi finalizado. O mesmo é acessível pela seguinte rota:

[POST] /group

JSON body:
{
  "groupName": "Group 1",
  "idForm" : 1,
  "idUBS" : 1,
  "users": ["1","2"]
}
